# Generated by Django 3.1.1 on 2021-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='snipet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='snipet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
