# Generated by Django 3.1.1 on 2021-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_events_postimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(blank=True, null=True, upload_to='post/images'),
        ),
    ]
