# Generated by Django 3.1.1 on 2021-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210603_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(choices=[('Early Years', 'Early Years'), ('Primary', 'Primary'), ('Secondary ', 'Secondary'), ('ICT', 'ICT'), ('Music', 'Music'), ('Others ', 'Other')], default='Early Years', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='postition',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Front Desk', 'Front Desk'), ('Cashier', 'Cashier'), ('Care Unit', 'Care Unit'), ('Security ', 'Security'), ('Nanny ', 'Nanny')], default='Teacher', max_length=100),
        ),
    ]
