# Generated by Django 3.1.1 on 2021-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210604_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='postition',
        ),
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Front Desk', 'Front Desk'), ('Cashier', 'Cashier'), ('Care Unit', 'Care Unit'), ('Security ', 'Security'), ('Nanny ', 'Nanny')], default='Teacher', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='userimg',
            field=models.ImageField(blank=True, null=True, upload_to='post/user_images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, choices=[('Early Years', 'Early Years'), ('Primary', 'Primary'), ('Secondary ', 'Secondary'), ('ICT', 'ICT'), ('Music', 'Music'), ('Others ', 'Others')], default='Early Years', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='post/user_cv'),
        ),
    ]
