# Generated by Django 3.1.1 on 2021-06-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210605_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='postimg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='postimg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userimg',
            new_name='image',
        ),
    ]
