# Generated by Django 3.1.1 on 2021-06-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20210610_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='comments',
            new_name='about',
        ),
    ]
