# Generated by Django 3.1.1 on 2021-06-11 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210611_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
