# Generated by Django 3.1.1 on 2021-06-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20210613_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
